# Generated by Django 5.1.3 on 2024-11-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_mlinputdata_remove_mlalgorithm_parent_endpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlinputdata',
            name='fnlwgt',
            field=models.IntegerField(default=77234),
            preserve_default=False,
        ),
    ]
